version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-v1-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-v1-
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Build production bundle
          command: yarn build
      - save-cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - build
            - cloudformation.json
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Provision infrastructure
          command: aws cloudformation deploy --stack-name spa-aws --template-file ./cloudformation.json
      - run:
          name: Deploy to S3
          command: aws s3 sync ./build s3://spa-aws

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: AWS
          filters:
            branches:
              only: master
